name: Deploy to S3 + CloudFront

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - '.github/**'
      - '.gitignore'
      - '**/MERGE*'

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::408433988572:role/github-oidc-hyrule-compendium-app-role
          role-session-name: github-actions
          aws-region: ca-central-1

      - name: Sync files to S3
        run: |
          aws s3 sync ./public s3://jean-static-site1 --delete \
            --exclude ".git/*" \
            --exclude ".github/*" \
            --exclude "README.md" \
            --exclude "package.json"

      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id E3SHAN1ERYUWEH \
            --paths "/*"